### ISSUE TITLE
Use a self hosted instance

### ISSUE THREAD

**Issue by SnakeGator** [stephane-r/Youtube-Audio-Player#143] opened 2021-05-26 18:02 UTC
Is there a way, or can a way be added, to use a self hosted instance of invidious with HoloPlay?

**Comment by stephane-r** [comment] 2021-05-27 06:10
Hey @SnakeGator 

This feature is on my todo and will be released soon :)

**Comment by stephane-r** [comment] 2021-05-29 10:01
Hello @SnakeGator 

The release will be published soon. It will be possible to add several instances and delete them.

Here is an example with a local instance of Invidious : 

![holoplay-custom-instance](https://user-images.githubusercontent.com/4712791/120066164-8af5c000-c075-11eb-975e-d13ad1b91c4e.gif)

**Comment by SnakeGator** [comment] 2021-05-29 21:26
Cool, thanks!

Good work on the app too, when an instance is working the app works well but I often have to switch instances so hopefully this will make things a bit more stable.

**Comment by stephane-r** [comment] 2021-06-01 11:52
Feature released on [1.10.1](https://github.com/stephane-r/HoloPlay/releases/tag/1.10.1) :)

Updated will be available in ~48-72h if you use Fdroid. Now for github apk file :+1: 

Thank you

**Comment by SnakeGator** [comment] 2021-06-01 21:09
Thanks for the update.

Are there any configuration changes I need to make on my instance to to get it going properly?  Currently, thumbnails don't load and the now playing interface doesn't appear.

**Comment by stephane-r** [comment] 2021-06-02 03:43
Only add your url on settings screen. 

With my private instance it working. Is it possible to share me your url (on PM) for run some test ?

**Comment by stephane-r** [comment] 2021-06-04 20:10
Hey @SnakeGator 

Thank you for sharing your domain.

I've test your API and the problem is with your configuration. The empty image is about domain URL with the port 3000. See : https://YOUR-DOMAIN.net/api/v1/search?q=eminem%20live&type=video (replace with your domain :))

Example :  

- wrong : https://YOUR-DOMAIN.net:3000/vi/ldWvm-ZqKaY/maxres.jpg
- the correct is : https://YOUR-DOMAIN.net/vi/ldWvm-ZqKaY/maxres.jpg

It also seems that other data does not go up, like the popular API: https://YOUR-DOMAIN.net/api/v1/popular

I think if you adjust your configuration by removing the port from your URLs, everything should work better :)  Could you keep me informed when you update this ?

**Comment by SnakeGator** [comment] 2021-06-04 20:40
Oh wow, my bad.  I didn't have 'external_port: 443' set properly to run behind my reverse proxy.

Thanks for finding that for me. After making that change, thumbnails and the now playing interface both load properly.

And again, thanks for the great work on the app.

**Comment by stephane-r** [comment] 2021-06-04 20:47
No problem :)

Thank you :+1:

**Closed as completed by stephane-r** 2021-06-04 20:47 UTC
